/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */


@class LTController;

@interface LTAppDelegate : NSObject {
	LTController *_controller;	// 4 = 0x4
	BOOL _ignorePlayPauseEvents;	// 8 = 0x8
}
@property(assign) BOOL ignorePlayPauseEvents;	// G=0x1526d; S=0x1527d; converted property
- (void)applicationDidFinishLaunching:(id)application;	// 0x15c69
- (void)completeNormalApplicationDidFinishLaunching;	// 0x15ac1
- (void)dealloc;	// 0x16039
// converted property getter: - (BOOL)ignorePlayPauseEvents;	// 0x1526d
// converted property setter: - (void)setIgnorePlayPauseEvents:(BOOL)events;	// 0x1527d
@end

@interface LTAppDelegate (Private)
- (void)_checkNetworkTime;	// 0x15305
- (void)_createGeniusPlaylist;	// 0x16771
- (void)_createOnTheGoPlaylist;	// 0x166f5
- (void)_musicStoreNotification:(id)notification;	// 0x167a1
- (void)_postMediaHostBootstrap;	// 0x16081
- (void)_registerAccessibilitySettings;	// 0x152e5
- (void)_registerAccountTypes;	// 0x15959
- (void)_registerAirTunesPlayer;	// 0x158e9
- (void)_registerHomeShareManager;	// 0x154d1
- (void)_registerParentalControls;	// 0x1551d
- (void)_timeChangeNotification:(id)notification;	// 0x1528d
@end

